spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CrazyAnts
    username: CrazyAnts
    password: CrazyAnts
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or "validate", "create", "create-drop"
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
